name: hulutaxi_driver
description: HuluTaxi Driver App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.0.1
  # Value equality
  equatable: ^2.0.3
  #Functional programming
  dartz: ^0.10.1
  #Connection
  data_connection_checker: ^0.3.4
  # Remote API
  http: ^0.13.4
  # Local cache
  shared_preferences: ^2.0.13
  # GetX router
  get: ^4.6.1
  # SVG
  flutter_svg: ^1.0.3
  # Loading
  flutter_spinkit: ^5.1.0
  # Splash
  flutter_native_splash: ^2.1.5
  #Slider
  carousel_slider: ^4.0.0
  #OTP
  pin_code_fields: ^7.4.0
  #Lottie Animation
  lottie: ^1.3.0
  #Scanner
  qr_code_scanner: ^0.7.0
  #WebView
  webview_flutter: ^3.0.2
  #ImagePicker
  image_picker: ^0.8.5
  #FilePicker
  file_picker: ^4.5.1
  #Http
  http_parser: ^4.0.0
  #File Upload
  dio: ^4.0.6
  #Rating bar
  flutter_rating_bar: ^4.0.0
  #Google Maps
  google_maps_flutter: ^2.1.4
  #permission
  permission_handler: ^9.2.0
  #Image cache
  cached_network_image: ^3.2.0
  #Number Format
  intl: ^0.17.0
  #Chart
  charts_flutter: ^0.12.0

  cupertino_icons: ^1.0.4
  stacked: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  flutter_lints: ^1.0.4
  #Icon Launcher
  flutter_launcher_icons:
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/anim/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#00b04e"
  remove_alpha_ios: true