import 'package:get/get.dart';

class LanguageTranslate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'strRegister': 'REGISTER WITH PHONE',
          'strLogin': 'LOGIN',
          'strAddPhotoTitle': 'Profile Photo',
          'strAddPhotoSub': 'Add Your Photo',
          'strAddVehicleTitle': 'Add Vehicle',
          'strBack': 'Back',
          'strContinue': 'Continue',
          'strResend': 'Resend Code',
          'strResendTimer': 'in 0 seconds',
          'strGreetingFirst': 'Hello, nice to meet you',
          'strGreetingSecondLogin': 'Login To HuluTaxi!',
          'strGreetingThirdLogin':
              'Please enter the phone number that you registered with.',
          'strGreetingSecondRegistration': 'Join HuluTaxi!',
          'strOtpFirst': 'Phone Verification',
          'strOtpSecond': 'Enter your OTP code',
          'strOtpThird': 'Enter the 5-digit code sent to you at ',
          'strModel': 'Model',
          'strColor': 'Color',
          'strRegisterVehicle': 'Register Vehicle',
          'strAgree': 'I agree to the',
          'strTerms': 'Terms & Conditions',
          'strThanks': 'Thank You!',
          'strWaitingTxt':
              'Thank you for submitting the required documents. We are evaluating your documents, you will receive a notification when your account is activated.',
          'strFinish': 'Finish',
          'strDoc': 'Driver Documents',
          'strDocReq': 'Required Document',
          'strUpload': 'Upload',
          'strWallet': 'Wallet',
          'strTripHistory': 'Trip History',
          'strEarnings': 'Earnings',
          'strDocuments': 'Documents',
          'strMyAccount': 'My Account',
          'strHuluCoin': 'HuluCoin',
          'strFeedback': 'Feedback',
          'strTheme': 'Theme',
          'strLanguage': 'Language',
          'strAccountDetailsTitle': 'ACCOUNT DETAILS',
          'strVehicleDetailsTitle': 'VEHICLE DETAILS',
          'strPhoneNoTitle': 'PHONE NO',
          'strReferralTitle': 'REFERRAL CODE',
          'strModelTitle': 'MODEL',
          'strColorTitle': 'COLOR',
          'strPlateNoTitle': 'PLATE NO',
          'strFeedbackType': 'Feedback Type',
          'strUrgencyLevel': 'Urgency Level',
          'strPromptFeedback': 'Enter feedback',
          'strSend': 'Send',
          'strDeposit': 'Deposit',
          'strWalletNo': '9834 7502 1684 2984',
          'strWalletMember': 'Member Since',
          'strWalletDate': '05/22',
          'strWalletBalance': 'Balance',
          'strBirr': 'Birr',
          'strKm': 'KM',
          'strTrips': 'Trips',
          'strBuyAirtime': 'Buy Airtime',
          'strFuelCoupon': 'Fuel Coupon',
          'strFuelCouponMsg':
              'Head to our main office to convert your HuluCoin to fuel coupons.',
          'str0': '0',
          'strCurrentBalance': 'Current Balance',
          'strToday': 'Today',
          'strTripDetail': 'Trip Details',
          'strDate': 'Date',
          'strTime': 'Time',
          'strPrice': 'Price',
          'strDistance': 'Distance',
          'strStatus': 'Status',
          'strComingSoon': 'Coming Soon!',
          'strSave': 'Save',
          'strCancel': 'Cancel',
          'strSubmit': 'Submit',
          'strCoinDesc':
              'Please pick one of the available mobile cards from below.',
          'strCoin50': '50 Br',
          'strCoin100': '100 Br',
          'strAirtimeSuccessStart': 'successfully began transferring to',
          'strAirtimeSuccessEnd':
              "from your HuluCoin balance. You'll receive notification when the airtime is added to your card.",
          'strOnlineHrs': "Online Hrs",
          'strLogout': "Logout",
          'strLogoutMsg': "Are you sure you want to logout from HuluTaxi?",
          'strOffline': "You're Offline",
          'strOnline': "You're Online",
          'strStreetPickUp': "Street Pickup",
          'strPickingUp': "Picking Up",
          'strArrived': "Arrived",
          'strCancelTrip': "Cancel Trip",
          'strAcceptTap': "Tap to Accept",
          'strDecline': "Decline",
          'strSwipeStart': "Swipe to Start",
          'strWaiting': 'Waiting',
          'strDriving': 'Driving',
          'strSwipeComplete': 'Swipe to Complete',
          'strSwipeComplete': 'Swipe to Complete',
          'strSelectLanguage': 'Select Languages',
          'strCurrentLanguage': 'Current Language',
          /*
          *
          *  * */
          'errMsgServer': 'Server Failure',
          'errMsgCache': 'Cache Failure',
          'errMsgConnection':
              'Unable to connect to the internet. Please check your connection.',
          'errMsgUnknown': 'Some error occurred. Please, try again!',
          'errMsgLogout':
              'Sorry, your account has been logged out of. Please login!',
          'errMsgPhone': 'Phone number starts with the digit 9 or 7!',
          'errMsgEmptyFirst': 'Please enter first name!',
          'errMsgEmptyFather': "Please enter father's name!",
          'errMsgEmptyGrandfather': "Please enter grandfather's name!",
          'errMsgEmptyPhone': "Please enter a phone number!",
          'errTerms': 'Please accept terms and conditions!',
          'errMsgModel': "Please select your car's model!",
          'errMsgColor': "Please select your car's color!",
          'errMsgEmptyPlateNo': "Please enter your car's plate number!",
          'errMsgEmptyMakeYear': "Please enter your car's make year!",
          'errMsgValidPlateNo': "Please enter a valid plate number!",
          'errMsgValidMakeYear': "Please enter a valid make year!",
          'errMsgPic': "Picture not picked. Please try again!",
          'errMsgFeedbackType': "Please select feedbackType",
          'errMsgUrgencyLevel': "Please select urgency level!",
          'errMsgEmptyFeedback': "Please enter feedback!",
          'errMsgAirtime':
              'Sorry, airtime exchange service is not available at the moment. Please, try again a bit later!',
          'errMsgEmptyLocation': 'Please enter a location!',
          /*
          *
          *  * */
          'strPromptPhone': 'Phone Number',
          'strPromptFirstName': 'First Name',
          'strPromptFatherName': "Father's Name",
          'strPromptGFatherName': "Grandfather's Name",
          'strPromptReferralCode': 'Referral Code',
          'strPromptMakeYear': 'Make Year',
          'strPromptLocationDropOff': 'Drop off Location',
        },
        /*
        *
        *
        *
        *  */
        'am_ET': {
          'strRegister': 'በስልክ ይመዝገቡ',
          'strLogin': 'ግባ',
          'strAddPhotoTitle': 'የመገለጫ ፎቶ',
          'strAddPhotoSub': 'ፎቶዎን ያክሉ',
          'strAddVehicleTitle': 'ተሽከርካሪ ያክሉ',
          'strBack': 'ተመለስ',
          'strContinue': 'ቀጥል',
          'strResend': 'ኮድ እንደገና ላክ',
          'strResendTimer': 'ከ 0 ሰከንድ በኋላ',
          'strGreetingFirst': 'ሰላም! ስለተዋወቅን ደስ ብሎናል',
          'strGreetingSecondLogin': 'ወደ ሁሉታክሲ ይግቡ!',
          'strGreetingThirdLogin':
              'እባክዎ የተመዘገቡበትን ስልክ ቁጥር ያስገቡ።',
          'strGreetingSecondRegistration': 'ሁሉታክሲን ይቀላቀሉ!',
          'strOtpFirst': 'Phone Verification',
          'strOtpSecond': 'Enter your OTP code',
          'strOtpThird': 'Enter the 5-digit code sent to you at ',
          'strModel': 'Model',
          'strColor': 'Color',
          'strRegisterVehicle': 'Register Vehicle',
          'strAgree': 'I agree to the',
          'strTerms': 'Terms & Conditions',
          'strThanks': 'Thank You!',
          'strWaitingTxt':
              'Thank you for submitting the required documents. We are evaluating your documents, you will receive a notification when your account is activated.',
          'strFinish': 'Finish',
          'strDoc': 'Driver Documents',
          'strDocReq': 'Required Document',
          'strUpload': 'Upload',
          'strWallet': 'Wallet',
          'strTripHistory': 'Trip History',
          'strEarnings': 'Earnings',
          'strDocuments': 'Documents',
          'strMyAccount': 'My Account',
          'strHuluCoin': 'HuluCoin',
          'strFeedback': 'Feedback',
          'strTheme': 'Theme',
          'strLanguage': 'Language',
          'strAccountDetailsTitle': 'ACCOUNT DETAILS',
          'strVehicleDetailsTitle': 'VEHICLE DETAILS',
          'strPhoneNoTitle': 'PHONE NO',
          'strReferralTitle': 'REFERRAL CODE',
          'strModelTitle': 'MODEL',
          'strColorTitle': 'COLOR',
          'strPlateNoTitle': 'PLATE NO',
          'strFeedbackType': 'Feedback Type',
          'strUrgencyLevel': 'Urgency Level',
          'strPromptFeedback': 'Enter feedback',
          'strSend': 'Send',
          'strDeposit': 'Deposit',
          'strWalletNo': '9834 7502 1684 2984',
          'strWalletMember': 'Member Since',
          'strWalletDate': '05/22',
          'strWalletBalance': 'Balance',
          'strBirr': 'Birr',
          'strKm': 'KM',
          'strTrips': 'Trips',
          'strBuyAirtime': 'Buy Airtime',
          'strFuelCoupon': 'Fuel Coupon',
          'strFuelCouponMsg':
              'Head to our main office to convert your HuluCoin to fuel coupons.',
          'str0': '0',
          'strCurrentBalance': 'Current Balance',
          'strToday': 'Today',
          'strTripDetail': 'Trip Details',
          'strDate': 'Date',
          'strTime': 'Time',
          'strPrice': 'Price',
          'strDistance': 'Distance',
          'strStatus': 'Status',
          'strComingSoon': 'Coming Soon!',
          'strSave': 'Save',
          'strCancel': 'Cancel',
          'strSubmit': 'Submit',
          'strCoinDesc':
              'Please pick one of the available mobile cards from below.',
          'strCoin50': '50 Br',
          'strCoin100': '100 Br',
          'strAirtimeSuccessStart': 'successfully began transferring to',
          'strAirtimeSuccessEnd':
              "from your HuluCoin balance. You'll receive notification when the airtime is added to your card.",
          'strOnlineHrs': "Online Hrs",
          'strLogout': 'ውጣ',
          'strLogoutMsg': 'እርግጠኛ ነዎት ከሁሉታክሲ መውጣት ይፈልጋሉ?',
          'strOffline': 'ከመስመር ውጭ ነዎት',
          'strOnline': 'መስመር ላይ ነዎት',
          'strStreetPickUp': "Street Pickup",
          'strPickingUp': "Picking Up",
          'strArrived': "Arrived",
          'strCancelTrip': "Cancel Trip",
          'strAcceptTap': "Tap to Accept",
          'strDecline': "Decline",
          'strSwipeStart': "Swipe to Start",
          'strWaiting': 'Waiting',
          'strDriving': 'Driving',
          'strSwipeComplete': 'Swipe to Complete',
          'strSelectLanguage': 'Select Languages',
          'strCurrentLanguage': 'Current Language',
          /*
          *
          *  * */
          'errMsgServer': 'Server Failure',
          'errMsgCache': 'Cache Failure',
          'errMsgConnection':
              'Unable to connect to the internet. Please check your connection.',
          'errMsgUnknown': 'Some error occurred. Please, try again!',
          'errMsgLogout':
              'Sorry, your account has been logged out of. Please login!',
          'errMsgPhone': 'Phone number starts with the digit 9 or 7!',
          'errMsgEmptyFirst': 'Please enter first name!',
          'errMsgEmptyFather': "Please enter father's name!",
          'errMsgEmptyGrandfather': "Please enter grandfather's name!",
          'errMsgEmptyPhone': "Please enter a phone number!",
          'errTerms': 'Please accept terms and conditions!',
          'errMsgModel': "Please select your car's model!",
          'errMsgColor': "Please select your car's color!",
          'errMsgEmptyPlateNo': "Please enter your car's plate number!",
          'errMsgEmptyMakeYear': "Please enter your car's make year!",
          'errMsgValidPlateNo': "Please enter a valid plate number!",
          'errMsgValidMakeYear': "Please enter a valid make year!",
          'errMsgPic': "Picture not picked. Please try again!",
          'errMsgFeedbackType': "Please select feedbackType",
          'errMsgUrgencyLevel': "Please select urgency level!",
          'errMsgEmptyFeedback': "Please enter feedback!",
          'errMsgAirtime':
              'Sorry, airtime exchange service is not available at the moment. Please, try again a bit later!',
          'errMsgEmptyLocation': 'Please enter a location!',
          /*
          *
          *  * */
          'strPromptPhone': 'የስልክ ቁጥር',
          'strPromptFirstName': 'ስም',
          'strPromptFatherName': 'የአባት ስም',
          'strPromptGFatherName': 'የአያት ስም',
          'strPromptReferralCode': 'ሪፈራል ኮድ',
          'strPromptMakeYear': 'የምርት ዓመት',
          'strPromptLocationDropOff': 'መሄጃ ቦታ',
        }
      };
}
