import 'package:get/get.dart';

class LanguageTranslate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'strRegister': 'REGISTER WITH PHONE',
          'strLogin': 'LOGIN',
          'strAddPhotoTitle': 'Profile Photo',
          'strAddPhotoSub': 'Add Your Photo',
          'strAddVehicleTitle': 'Add Vehicle',
          'strBack': 'Back',
          'strContinue': 'Continue',
          'strResend': 'Resend Code',
          'strResendTimer': 'in 0 seconds',
          'strGreetingFirst': 'Hello, nice to meet you',
          'strGreetingSecondLogin': 'Login To HuluTaxi!',
          'strGreetingThirdLogin':
              'Please enter the phone number that you registered with.',
          'strGreetingSecondRegistration': 'Join HuluTaxi!',
          'strOtpFirst': 'Phone Verification',
          'strOtpSecond': 'Enter your OTP code',
          'strOtpThird': 'Enter the 5-digit code sent to you at ',
          'strModel': 'Model',
          'strColor': 'Color',
          'strRegisterVehicle': 'Register Vehicle',
          'strAgree': 'I agree to the',
          'strTerms': 'Terms & Conditions',
          'strThanks': 'Thank You!',
          'strWaitingTxt':
              'Thank you for submitting the required documents. We are evaluating your documents, you will receive a notification when your account is activated.',
          'strFinish': 'Finish',
          'strDoc': 'Driver Documents',
          'strDocReq': 'Required Document',
          'strUpload': 'Upload',
          'strWallet': 'Wallet',
          'strTripHistory': 'Trip History',
          'strEarnings': 'Earnings',
          'strDocuments': 'Documents',
          'strMyAccount': 'My Account',
          'strHuluCoin': 'HuluCoin',
          'strFeedback': 'Feedback',
          'strTheme': 'Theme',
          'strLanguage': 'Language',
          'strAccountDetailsTitle': 'ACCOUNT DETAILS',
          'strVehicleDetailsTitle': 'VEHICLE DETAILS',
          'strPhoneNoTitle': 'PHONE NO',
          'strReferralTitle': 'REFERRAL CODE',
          'strModelTitle': 'MODEL',
          'strColorTitle': 'COLOR',
          'strPlateNoTitle': 'PLATE NO',
          'strFeedbackType': 'Feedback Type',
          'strUrgencyLevel': 'Urgency Level',
          'strPromptFeedback': 'Enter feedback',
          'strSend': 'Send',
          'strDeposit': 'Deposit',
          'strWalletMember': 'Member Since',
          'strWalletBalance': 'Balance',
          'strBirr': 'Birr',
          'strKm': 'KM',
          'strTrips': 'Trips',
          'strBuyAirtime': 'Buy Airtime',
          'strFuelCoupon': 'Fuel Coupon',
          'strCurrentBalance': 'Current Balance',
          'strToday': 'Today',
          'strTripDetail': 'Trip Details',
          'strDate': 'Date',
          'strTime': 'Time',
          'strPrice': 'Price',
          'strDistance': 'Distance',
          'strStatus': 'Status',
          'strComingSoon': 'Coming Soon!',
          'strSave': 'Save',
          'strCancel': 'Cancel',
          'strSubmit': 'Submit',
          'strCoinDesc':
              'Please pick one of the available mobile cards from below.',
          'strCoin50': '50 Br',
          'strCoin100': '100 Br',
          'strOnlineHrs': "Online Hrs",
          'strLogout': "Logout",
          'strOffline': "You're Offline",
          'strOnline': "You're Online",
          'strStreetPickUp': 'Street Pickup',
          'strPickingUp': 'Picking Up',
          'strArrived': 'Arrived',
          'strCancelTrip': 'Cancel Trip',
          'strAcceptTap': 'Tap to Accept',
          'strDecline': 'Decline',
          'strSwipeStart': 'Swipe to Start',
          'strWaiting': 'Waiting',
          'strDriving': 'Driving',
          'strSwipeComplete': 'Swipe to Complete',
          'strSelectLanguage': 'Select Languages',
          'strCurrentLanguage': 'Current Language',
          /*
          *
          *  * */

          'msgFuelCoupon':
              'Head to our main office to convert your HuluCoin to fuel coupons.',
          'msgAirtimeSuccessStart': 'successfully began transferring to',
          'msgAirtimeSuccessEnd':
              "from your HuluCoin balance. You'll receive notification when the airtime is added to your card.",
          'msgLogout': "Are you sure you want to logout from HuluTaxi?",
          /*
          *
          *  * */
          'errMsgServer': 'Server Failure',
          'errMsgCache': 'Cache Failure',
          'errMsgConnection':
              'Unable to connect to the internet. Please check your connection.',
          'errMsgUnknown': 'Some error occurred. Please, try again!',
          'errMsgLogout':
              'Sorry, your account has been logged out of. Please login!',
          'errMsgPhone': 'Phone number starts with the digit 9 or 7!',
          'errMsgEmptyFirst': 'Please enter first name!',
          'errMsgEmptyFather': "Please enter father's name!",
          'errMsgEmptyGrandfather': "Please enter grandfather's name!",
          'errMsgEmptyPhone': "Please enter a phone number!",
          'errTerms': 'Please accept terms and conditions!',
          'errMsgModel': "Please select your car's model!",
          'errMsgColor': "Please select your car's color!",
          'errMsgEmptyPlateNo': "Please enter your car's plate number!",
          'errMsgEmptyMakeYear': "Please enter your car's make year!",
          'errMsgValidPlateNo': "Please enter a valid plate number!",
          'errMsgValidMakeYear': "Please enter a valid make year!",
          'errMsgPic': "Picture not picked. Please try again!",
          'errMsgFeedbackType': "Please select feedbackType",
          'errMsgUrgencyLevel': "Please select urgency level!",
          'errMsgEmptyFeedback': "Please enter feedback!",
          'errMsgAirtime':
              'Sorry, airtime exchange service is not available at the moment. Please, try again a bit later!',
          'errMsgEmptyLocation': 'Please enter a location!',
          /*
          *
          *  * */
          'strPromptPhone': 'Phone Number',
          'strPromptFirstName': 'First Name',
          'strPromptFatherName': "Father's Name",
          'strPromptGFatherName': "Grandfather's Name",
          'strPromptReferralCode': 'Referral Code',
          'strPromptMakeYear': 'Make Year',
          'strPromptLocationDropOff': 'Drop off Location',
        },
        /*
        *
        *
        *
        *  */
        'am_ET': {
          'strRegister': 'በስልክ ይመዝገቡ',
          'strLogin': 'ግባ',
          'strAddPhotoTitle': 'የመገለጫ ፎቶ',
          'strAddPhotoSub': 'ፎቶዎን ያክሉ',
          'strAddVehicleTitle': 'ተሽከርካሪ ያክሉ',
          'strBack': 'ተመለስ',
          'strContinue': 'ቀጥል',
          'strResend': 'ኮድ እንደገና ላክ',
          'strResendTimer': 'ከ 0 ሰከንድ በኋላ',
          'strGreetingFirst': 'ሰላም! ስለተዋወቅን ደስ ብሎናል',
          'strGreetingSecondLogin': 'ወደ ሁሉታክሲ ይግቡ!',
          'strGreetingThirdLogin': 'እባክዎ የተመዘገቡበትን ስልክ ቁጥር ያስገቡ።',
          'strGreetingSecondRegistration': 'ሁሉታክሲን ይቀላቀሉ!',
          'strOtpFirst': 'የስልክ ማረጋገጫ',
          'strOtpSecond': 'የእርስዎን ኦቲፒ ኮድ ያስገቡ',
          'strOtpThird': 'ያስገቡ ባለ 5-አሃዝ ኮድ ልከናል ወደ ',
          'strModel': 'ሞዴል',
          'strColor': 'ቀለም',
          'strRegisterVehicle': 'ተሽከርካሪ ምዝገባ',
          'strAgree': 'እስማማለሁ ለ ',
          'strTerms': 'ውሎች እና ህጋዊ ቅድመ ሁኔታዎች',
          'strThanks': 'አናመሰግናለን!',
          'strWaitingTxt':
              'አስፈላጊ ሰነዶችን ስላስገቡ እናመሰግናለን። ሰነዶችዎን እየገመገምን ነው፣ መለያዎ ሲረጋገጥ ማሳወቂያ ይደርሰዎታል።',
          'strFinish': 'ጨርስ',
          'strDoc': 'የሹፌር ሰነዶች',
          'strDocReq': 'አስፈላጊ ሰነድ',
          'strUpload': 'አክል',
          'strWallet': 'ዋሌት',
          'strTripHistory': 'የጉዞ መረጃ',
          'strEarnings': 'ገቢዎች',
          'strDocuments': 'ሰነዶች',
          'strMyAccount': 'የእኔ አካውንት',
          'strHuluCoin': 'ሁሉኮይን',
          'strFeedback': 'አስተያየት',
          'strTheme': 'ገጽታ',
          'strLanguage': 'ቋንቋ',
          'strAccountDetailsTitle': 'የመለያ ዝርዝሮች',
          'strVehicleDetailsTitle': 'የተሽከርካሪ ዝርዝሮች',
          'strPhoneNoTitle': 'ስልክ ቁጥር',
          'strReferralTitle': 'ሪፈራል ኮድ',
          'strModelTitle': 'ሞዴል',
          'strColorTitle': 'ቀለም',
          'strPlateNoTitle': 'የሰሌዳ ቁጥር',
          'strFeedbackType': 'የአስተያየት አይነት',
          'strUrgencyLevel': 'የአስቸኳይነት ደረጃ',
          'strSend': 'ላክ',
          'strDeposit': 'ገንዘብ አስገባ',
          'strWalletMember': 'አባል ጅማሬ',
          'strWalletBalance': 'ሂሳብ',
          'strBirr': 'ብር',
          'strKm': 'ኪ.ሜ',
          'strTrips': 'ጉዞዎች',
          'strBuyAirtime': 'ሞባይል ካርድ',
          'strFuelCoupon': 'የነዳጅ ኩፖን',
          'strCurrentBalance': 'ሒሳብ',
          'strToday': 'ዛሬ',
          'strTripDetail': 'የጉዞ ዝርዝሮች',
          'strDate': 'ቀን',
          'strTime': 'ጊዜ',
          'strPrice': 'ዋጋ',
          'strDistance': 'ርቀት',
          'strStatus': 'ሁኔታ',
          'strComingSoon': 'በቅርብ ቀን!',
          'strSave': 'አስቀምጥ',
          'strCancel': 'ሰርዝ',
          'strSubmit': 'አስገባ',
          'strCoinDesc': 'እባክዎ ከታች ካሉት የሞባይል ካርዶች አንዱን ይምረጡ።',
          'strCoin50': '50 ብር',
          'strCoin100': '100 ብር',
          'strOnlineHrs': 'የመስመር ላይ ሰዓት',
          'strLogout': 'ውጣ',
          'strOffline': 'ከመስመር ውጭ ነዎት',
          'strOnline': 'መስመር ላይ ነዎት',
          'strStreetPickUp': 'ጉዞ ጀምር',
          'strPickingUp': 'በማሳፈር ላይ',
          'strArrived': 'ደርሰዋል',
          'strCancelTrip': 'ጉዞ ሰርዝ',
          'strAcceptTap': 'ለመቀበል ይሄን ይጫኑ',
          'strDecline': 'አትቀበል',
          'strSwipeStart': 'ለመጀመር ይሄን ያንቀሳቅሱ',
          'strWaiting': 'በመጠበቅ ላይ',
          'strDriving': 'በመንዳት ላይ',
          'strSwipeComplete': 'ለማጠናቅቅ ይሄን ያንቀሳቅሱ',
          'strSelectLanguage': 'ቋንቋ ይምረጡ',
          'strCurrentLanguage': 'የአሁኑ ቋንቋ',
          /*
          *
          *  * */
          'msgFuelCoupon': 'የእርስዎን ሁሉኮይን ወደ ነዳጅ ኩፖኖች ለመቀየር ወደ ዋናው ቢሮአችን ይሂዱ።',
          'msgAirtimeSuccessStart': 'ከሁሉኮይን ቀሪ ሂሳብዎ በተሳካ ሁኔታ ወደ',
          'msgAirtimeSuccessEnd':
              'ማስተላለፍ ተጀምሯል። የአየር ሰዓቱ በካርድዎ ላይ ሲጨመር ማሳወቂያ ይደርስዎታል።',
          'msgLogout': 'እርግጠኛ ነዎት ከሁሉታክሲ መውጣት ይፈልጋሉ?',
          /*
          *
          *  * */
          'errMsgServer': 'የመስመር የውሂብ ጎታ ብልሽት',
          'errMsgCache': 'የውሂብ ጎታ ብልሽት',
          'errMsgConnection': 'ከበይነመረቡ ጋር መገናኘት አልተቻለም። እባክዎ ግንኙነትዎን ያረጋግጡ።',
          'errMsgUnknown': 'ብልሽት ተከስቷል። እባክዎ ዳግም ይሞክሩ!',
          'errMsgLogout': 'ይቅርታ፣ መለያዎ ወጥቶዋል። እባክዎ ዳግም ይግቡ!',
          'errMsgPhone': 'ስልክ ቁጥር በዲጂት 9 ወይም 7 ይጀምራል!',
          'errMsgEmptyFirst': 'እባክዎን የመጀመሪያ ስምዎን ያስገቡ!',
          'errMsgEmptyFather': 'እባክዎን የአባትዎን ስም ያስገቡ!',
          'errMsgEmptyGrandfather': 'እባክዎን የአያትዎን ስም ያስገቡ!',
          'errMsgEmptyPhone': 'እባክዎን ስልክ ቁጥር ያስገቡ!',
          'errTerms': 'እባክዎ ውሎችን እና ሁኔታዎችን ይቀበሉ!',
          'errMsgModel': 'እባክዎ የመኪናዎን ሞዴል ይምረጡ!',
          'errMsgColor': 'እባክዎ የመኪናዎን ቀለም ይምረጡ!',
          'errMsgEmptyPlateNo': 'እባክዎ የመኪናዎን የታርጋ ቁጥር ያስገቡ!',
          'errMsgEmptyMakeYear': 'እባክዎ የመኪናዎን የምርት አመት ያስገቡ!',
          'errMsgValidPlateNo': 'እባክዎ ትክክለኛ የሰሌዳ ቁጥር ያስገቡ!',
          'errMsgValidMakeYear': 'እባክዎ ትክክለኛ የምርት አመት ያስገቡ!',
          'errMsgPic': 'ምስል አልተመረጠም። እባክዎ ዳግም ይሞክሩ!',
          'errMsgFeedbackType': 'እባክዎ የአስተያየት አይነት ይምረጡ!',
          'errMsgUrgencyLevel': 'እባክዎ የአስቸኳይ ደረጃን ይምረጡ!',
          'errMsgEmptyFeedback': 'እባክዎ አስተያየት ያስገቡ!',
          'errMsgAirtime': 'ይቅርታ፣ የሞባይል ካርድ ልውውጥ አገልግሎት በአሁኑ ጊዜ የለም። እባክዎ ትንሽ ቆይተው ዳግም ይሞክሩ!',
          'errMsgEmptyLocation': 'እባክዎ ቦታ ያስገቡ!',
          /*
          *
          *  * */
          'strPromptPhone': 'የስልክ ቁጥር',
          'strPromptFirstName': 'ስም',
          'strPromptFatherName': 'የአባት ስም',
          'strPromptGFatherName': 'የአያት ስም',
          'strPromptReferralCode': 'ሪፈራል ኮድ',
          'strPromptMakeYear': 'የምርት ዓመት',
          'strPromptLocationDropOff': 'መሄጃ ቦታ',
          'strPromptFeedback': 'አስተያየትዎን ያስገቡ',
        }
      };
}
